paths:
  /api/products:
    get:
      summary: Obtiene todas los productos
      tags:
        - Products
      responses:
        200:
          description: Productos obtenidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Estado de la respuesta
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/product'
        500:
          description: Error interno del servidor
    post:
      summary: Crear un nuevo productos
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/createProduct'
      responses:
        201:
          description: Producto creado exitosament.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
                      
        500:
          description: Error interno del servidor.      
  /api/products/{pid}:
    get:
      summary: Obtiene un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string  
      responses:
        200:
          description: Producto obtenido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
        404:
          description: Producto no encontrado        
        500:
          description: Error interno del servidor
    put:
      summary: Actualiza un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/updateProduct'          
      responses:
        200:
          description: Producto actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productUpdate'
        404:
          description: Producto no encontrado        
        500:
          description: Error interno del servidor
    delete:
      summary: Eliminar un producto por su ID
      tags:
        - Products
      parameters:
        - in: path
          name: pid
          required: true
          description: ID del producto
          schema:
            type: string          
      responses:
        200:
          description: Producto Eliminado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/productDelete'
        404:
          description: Producto no encontrado        
        500:
          description: Error interno del servidor          
components:
  schemas:
    product:
      type: object
      properties:
        _id:
          type: string
          description: Identificador del producto en la base de datos.
        title:
          type: string
          description: Titulo del producto.
        description:
          type: string
          description: Descripción del producto.
        price:
          type: number
          description: Precio del producto.
        thumbnail:
          type: string
          description: Imagen del producto.
        code:
          type: string
          description: Codigo del producto.
        stock:
          type: number
          description: Cantidad de productos disponibles.
        status:
          type: boolean
          description: Estado del producto.
        category:
          type: string
          description: Categoria del producto.
        owner:
          type: string
          description: Propietario del producto.      
      example:
        owner: "admin"
        _id: "65584b8b9133776f26fe51e4"
        title: "producto prueba 1"
        description: "Este es un producto prueba 1"
        price: 300
        thumbnail: "Sin imagen"
        code: "abc1"
        stock: 25
        status: true
        category: "Zapatillas"
        createdAt: "2023-11-18T05:28:43.018Z"
        updatedAt: "2023-11-30T03:03:06.001Z"
    productUpdate:
      type: object
      properties:
        message:
          type: string
          description: Mesaje de confirmación.
        status:
          type: string
          description: status.
        statusCode:
          type: number
          description: statusCode.     
      example:
        message: Product successfully updated
        status: Success
        statusCode: 202
    productDelete:
      type: object
      properties:
        message:
          type: string
          description: Mesaje de confirmación.
        status:
          type: string
          description: status.
        statusCode:
          type: number
          description: statusCode.     
      example:
        message: Product successfully deleteded
        status: Success
        statusCode: 200
  requestBodies:
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: Titulo del producto.
        description:
          type: string
          description: Descripción del producto.
        price:
          type: number
          description: Precio del producto.
        thumbnail:
          type: string
          description: Imagen del producto.
        code:
          type: string
          description: Codigo del producto.
        stock:
          type: number
          description: Cantidad de productos disponibles.
        status:
          type: boolean
          description: Estado del producto.
        category:
          type: string
          description: Categoria del producto.
      example:
        title: "producto prueba premium 3"
        description: "Este es un producto prueba premium 2"
        price: 300
        thumbnail: "Sin imagen"
        code: "abc172"
        stock: 25
        status: true
        category: "Zapatillas"
        createdAt: "2023-11-18T05:28:43.018Z"
        updatedAt: "2023-11-30T03:03:06.001Z"
    updateProduct:
      type: object
      properties:
        description:
          type: string
          description: Descripción del producto.
        price:
          type: number
          description: Precio del producto.
        stock:
          type: number
          description: Cantidad de productos disponibles.
      example:
        description: "Este es un producto prueba premium 2"
        price: 300
        stock: 25   

 